name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: npm i -g pnpm@7.1.9
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run test
